modLoader="javafml"
loaderVersion="[${fml_min},)"
license="${mod_license}"
displayURL="${mod_homepage}"
issueTrackerURL="${mod_github}/issues"

[[mods]]
modId="cuneiform"
version="${mod_version}"
displayName="${mod_name}"
logoFile="cuneiform.png"
authors="Azmalent"
description="${mod_description}"

[[dependencies.cuneiform]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"

[[dependencies.cuneiform]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"